services:
  # Firebase Emulatorサービス（テスト専用）
  firebase-emulator-test:
    build:
      context: .
      dockerfile: firebase-emulator.test.Dockerfile
    ports:
      - '4000:4000' # Emulator UI (localhost:4000)
      - '8080:8080' # Firestore (UIアクセス用)
      - '9099:9099' # Auth (UIアクセス用)
    volumes:
      - .:/workspace
      - ./firebase-emulator-data:/workspace/firebase-emulator-data
    environment:
      - FIRESTORE_EMULATOR_HOST=0.0.0.0:8080
      - FIREBASE_AUTH_EMULATOR_HOST=0.0.0.0:9099
      # ローカルテストデータ使用設定
      - USE_TEST_DB_DATA=true
      # テストアカウントのメールアドレスはコード内で定義
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000']
      interval: 10s
      timeout: 5s
      retries: 3

  # Next.jsアプリ（テスト用）
  nextjs-test:
    build: .
    ports:
      - '3002:3000' # 開発サーバーと分離
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - NEXT_PUBLIC_API_MOCKING=disabled
      - FIRESTORE_EMULATOR_HOST=firebase-emulator-test:8080
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulator-test:9099
      - NEXT_PUBLIC_EMULATOR_MODE=true
      - NEXTAUTH_SECRET=test-secret-for-docker-testing
      - NEXTAUTH_URL=http://localhost:3002
      - NEXT_PUBLIC_TEST_USER_UID=test-user-1
      - NEXT_PUBLIC_TEST_ADMIN_UID=test-admin-1
      - FIREBASE_PROJECT_ID=todoapp-test
      # ローカルテストデータ使用設定
      - USE_TEST_DB_DATA=true
      # テストアカウントのメールアドレスはコード内で定義
    depends_on:
      firebase-emulator-test:
        condition: service_healthy



  # ITテスト実行用コンテナ
  integration-test:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - FIRESTORE_EMULATOR_HOST=firebase-emulator-test:8080
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulator-test:9099
      - FIREBASE_PROJECT_ID=todoapp-test
      - NEXT_PUBLIC_APP_URL=http://nextjs-test:3000
    depends_on:
      firebase-emulator-test:
        condition: service_healthy
      nextjs-test:
        condition: service_started
    command: sh -c "sleep 10 && npx vitest run tests/features/todo/api.integration.test.ts --config vitest.integration.config.ts"
    profiles:
      - test # プロファイルを使用してオプションで実行
