import type { Metadata } from 'next';
import './static/input.css';
import { Geist, Geist_Mono } from 'next/font/google';
import { MSWProvider } from '@/app/providers/MSWProvider';
import { SessionProvider } from '@/app/providers/SessionProvider';
import { MockIndicator } from '@/features/shared/components/elements/Mock/MockIndicator';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-sky-100`}
      >
        <SessionProvider>
          <MSWProvider>
            {children}
            <MockIndicator />
          </MSWProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
